version: 2
updates:
  - package-ecosystem: gomod
    directory: /s3-mirror/
    schedule:
      interval: daily
    rebase-strategy: disabled
    commit-message:
      prefix: "feat(deps)"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    rebase-strategy: disabled
    commit-message:
      prefix: "ci(deps)"
