name: 'S3 Github Release Mirror'
description: 'Download Files from Github releases and upload them to S3'
author: 'oliverbaehler@hotmail.com'
inputs:
  s3_bucket:
    description: 'S3 bucket to upload binaries'
    required: true
  config:
    description: 'YAML config file for binaries to download'
    required: false
    default: 'config.yaml'
  s3_region:
    description: 'S3 Region'
    required: true
  s3_access_key:
    description: 'S3 Access key ID'
    required: true
  s3_secret_key:
    description: 'S3 Secret access key'
    required: true
  s3_endpoint:
    description: 'S3 endpoint'
    required: true
  s3_tlssecure:
    description: 'Use TLS for the S3 endpoint'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--bucket'
    - ${{ inputs.s3_bucket }}
    - '--config'
    - ${{ inputs.config }}
    - '--region'
    - ${{ inputs.s3_region }}
    - '--access-key'
    - ${{ inputs.s3_access_key }}
    - '--secret-key'
    - ${{ inputs.s3_secret_key }}
    - '--endpoint'
    - ${{ inputs.s3_endpoint }}
    - '--tlssecure'
    - ${{ inputs.s3_tlssecure }}
branding:
  icon: 'download'
  color: 'blue'
