name: 'S3 Github Release Mirror'
description: 'Download Files from Github releases and upload them to S3'
author: 'oliverbaehler@hotmail.com'
inputs:
  s3_bucket:
    description: 'S3 bucket to upload binaries'
    required: false
  config:
    description: 'YAML config file for binaries to download'
    required: false
    default: 'config.yaml'
  s3_region:
    description: 'S3 Region'
    required: false
  s3_access_key:
    description: 'S3 Access key ID'
    required: false
  s3_secret_key:
    description: 'S3 Secret access key'
    required: false
  s3_endpoint:
    description: 'S3 endpoint'
    required: false
  s3_tlssecure:
    default: "true"
    description: 'Use TLS for the S3 endpoint'
    required: false
  log_level:
    description: 'Log level for script'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'download'
  color: 'blue'
